spring.application.name=resource-booking-system

spring.datasource.url=jdbc:mysql://localhost:3306/resource_booking
spring.datasource.username=root
spring.datasource.password=Pass@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# JWT
jwt.secret=ThisIsASecretKeyForResourceBookingSystem2026VerySecure
jwt.expiration=86400000

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html